ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
