ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
