ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
