ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/ ir_led/ ir_cut/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
