ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_rosy/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_csid.o
